### ISSUE TITLE
Update readme for updated type names

### ISSUE THREAD

**Issue by titushm** [RJ-Infinity/RJJSON#1]
JsonType is now JSONType.
id imagine other types have the wrong names but not sure.
maybe some docs on gitbook?

**Comment by RJ-Infinity** [comment]
What do you mean by "wrong names"? Why are the names wrong. I agree with the docs idea. Might add some soon.

**Comment by titushm** [comment]
A mismatch between the readme and the actual use

**Comment by RJ-Infinity** [comment]
ahh yes i see how that could be confusing i will update them

**Comment by RJ-Infinity** [comment]
i have added a seperate issue for the Docs (#2) and updated the readme
